service:
  name: mindless-example

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: src/handler.start
    events:
      - http:
          method: any
          path: /{proxy+}
